export const START_LOADING_DOMAIN = 'START_LOADING_DOMAIN'
export const END_LOADING_DOMAIN = 'END_LOADING_DOMAIN'
export const FETCH_ALL_DOMAIN = 'FETCH_ALL_DOMAIN'
export const DELETE_DOMAIN = 'DELETE_DOMAIN'