export const SURVEY_LIST_REQUEST = 'SURVEY_LIST_REQUEST'
export const SURVEY_LIST_SUCCESS ='SURVEY_LIST_SUCCESS'
export const SURVEY_LIST_FAIL ='SURVEY_LIST_FAIL'
export const SURVEY_LIST_RESET = 'SURVEY_LIST_RESET'

export const SURVEY_DELETE_REQUEST = 'SURVEY_DELETE_REQUEST'
export const SURVEY_DELETE_SUCCESS = 'SURVEY_DELETE_SUCCESS'
export const SURVEY_DELETE_FAIL = 'SURVEY_DELETE_FAIL'


export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'
export const FETCH_ALL = 'FETCH_ALL'
export const DELETE = 'DELETE'