export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

// specific for admin 

export const START_LOADING_USERS = 'START_LOADING_USERS'
export const END_LOADING_USERS = 'END_LOADING_USERS'
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS'
export const UPDATE_USERS = 'UPDATE_USERS'
export const DELETE_USERS = 'DELETE_USERS'


